services:
  app-dev:
    build: .
    image: hiilikartta-data-service
    env_file:
      - ./.env
    environment:
      REDIS_HOST: "redis-queue"
    ports:
      - "${APP_PORT}:80"
      - "${NOTEBOOK_PORT}:8888"
    volumes:
      - .:/app:z
      - ./.cache:/root/.cache
      - ./.vscode-server:/root/.vscode-server
      - python-dev:/root/dev
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.dev.sh"]
    restart: unless-stopped
    networks:
      - app-net
      - climate-map-network
    deploy:
      resources:
        limits:
          memory: 24G

    depends_on:
      state-db-dev:
        condition: service_started

  worker-dev:
    build: .
    image: hiilikartta-data-service
    # command: poetry run watchmedo auto-restart --directory='app' --recursive -- saq app.saq_worker.settings --workers ${SAQ_WORKERS_COUNT:-3} --web
    env_file:
      - ./.env
    environment:
      REDIS_HOST: "redis-queue"
    volumes:
      - ./project:/usr/src/app
      - .:/app:z
      - ./.cache:/root/.cache
    ports:
      - "${SAQ_WEB_PORT}:8080"
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/app/docker-entrypoint-worker.dev.sh"]
    networks:
      - app-net
      - climate-map-network
    depends_on:
      app-dev:
        condition: service_started
      redis-dev:
        condition: service_started

  redis-dev:
    image: redis:latest
    restart: unless-stopped
    networks:
      app-net:
        aliases:
          - redis-queue
    # volumes:
    #   - cache:/data

  state-db-dev:
    image: postgres:15-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${STATE_PG_DB}
      POSTGRES_USER: ${STATE_PG_USER}
      POSTGRES_PASSWORD: ${STATE_PG_PASSWORD}
    volumes:
      - ./data/state-db-dev:/var/lib/postgresql/data
    networks:
      - app-net

  state-db-test:
    image: postgres:15-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${STATE_PG_TEST_DB}
      POSTGRES_USER: ${STATE_PG_TEST_USER}
      POSTGRES_PASSWORD: ${STATE_PG_TEST_PASSWORD}
    volumes:
      - state-db-test-data:/var/lib/postgresql/data
    networks:
      - app-net


  # dashboard:
  #   build: .
  #   env_file:
  #     - ./.env
  #   image: hiilikartta-data-service
  #   command: poetry run celery --broker=redis://redis:6379/0 flower --port=5555
  #   volumes:
  #     - ./project:/usr/src/app
  #     - .:/app:z
  #     - ./.cache:/root/.cache
  #   ports:
  #     - 5556:5555
  #   depends_on:
  #     - app
  #     - redis
  #     - worker

networks:
  app-net:
  climate-map-network:
    external: true
volumes:
  python-dev:
    driver: local
  state-db-test-data:
#   poetry-cache:
