version: "3.8"

services:
  app:
    container_name: hiilikartta-data
    build: .
    env_file:
      - ./.env
    ports:
      - "${DEV_PORT}:80"
      - "${NOTEBOOK_PORT}:8888"
    volumes:
      - .:/app:z
      - poetry-cache:/root/.cache/pypoetry:z
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]

volumes:
  poetry-cache:
