version: "3.8"

services:
  app:
    container_name: hiilikartta-data
    build: .
    image: hiilikartta-data-service
    env_file:
      - ./.env
    ports:
      - "${DEV_PORT}:80"
      - "${NOTEBOOK_PORT}:8888"
    volumes:
      - .:/app:z
      - ./.cache:/root/.cache
      # - ./.conda-pkgs:/root/conda/pkgs
      - ./.vscode-server:/root/.vscode-server
      # - ${REMOTE_DB_SSH_KEY}:/root/.ssh/remote_db_rsa:z
      - ${GIT_SSH_KEY}:/root/.ssh/id_rsa:z
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    restart: unless-stopped
    networks:
      - climate-map-network
    deploy:
      resources:
        limits:
          memory: 24G

  worker:
    build: .
    container_name: hiilikartta-data-worker
    image: hiilikartta-data-service
    command: poetry run watchmedo auto-restart -d app/ -R -- saq app.saq_worker.settings -- --workers 3 --web
    env_file:
      - ./.env
    volumes:
      - ./project:/usr/src/app
      - .:/app:z
      - ./.cache:/root/.cache
    ports:
      - "${SAQ_WEB_PORT}:8080"
    restart: unless-stopped
    networks:
      - climate-map-network
    depends_on:
      app:
        condition: service_started
      redis:
        condition: service_started

  redis:
    container_name: hiilikartta-data-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - climate-map-network
    # volumes:
    #   - cache:/data

  pgbouncer-gis:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer-gis
    restart: unless-stopped
    environment:
      DB_HOST: ${GIS_PG_HOST}
      DB_PORT: ${GIS_PG_PORT}
      DB_USER: ${GIS_PG_USER}
      DB_PASSWORD: ${GIS_PG_PASSWORD}
      DB_NAME: ${GIS_PG_DB}
      AUTH_TYPE: scram-sha-256
      POOL_MODE: session
      MAX_CLIENT_CONN: 5
      DEFAULT_POOL_SIZE: 3
      SERVER_RESET_QUERY: "DISCARD ALL"
    networks:
      - climate-map-network

  pgbouncer-state:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer-state
    restart: unless-stopped
    environment:
      DB_HOST: ${STATE_PG_HOST}
      DB_PORT: ${STATE_PG_PORT}
      DB_USER: ${STATE_PG_USER}
      DB_PASSWORD: ${STATE_PG_PASSWORD}
      DB_NAME: ${STATE_PG_DB}
      AUTH_TYPE: scram-sha-256
      POOL_MODE: session
      MAX_CLIENT_CONN: 5
      DEFAULT_POOL_SIZE: 3
      SERVER_RESET_QUERY: "DISCARD ALL"
    networks:
      - climate-map-network

  # dashboard:
  #   build: .
  #   env_file:
  #     - ./.env
  #   image: hiilikartta-data-service
  #   command: poetry run celery --broker=redis://redis:6379/0 flower --port=5555
  #   volumes:
  #     - ./project:/usr/src/app
  #     - .:/app:z
  #     - ./.cache:/root/.cache
  #   ports:
  #     - 5556:5555
  #   depends_on:
  #     - app
  #     - redis
  #     - worker

networks:
  climate-map-network:
    external: true
# volumes:
#   poetry-cache:
