services:
  app-prod:
    restart: unless-stopped
    build: .
    env_file:
      - ./.env
    environment:
      REDIS_HOST: "redis-prod"
      REDIS_PORT: "6379"
    ports:
      - "8000:80"
    volumes:
      - .:/app:z
      - ./.cache:/root/.cache
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.prod.sh"]
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hiilikartta-data-service.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.hiilikartta-data-service.entrypoints=websecure"
      - "traefik.http.routers.hiilikartta-data-service.tls.certresolver=myresolver"
      - "traefik.http.services.hiilikartta-data-service.loadbalancer.server.port=80"


  worker-prod:
    build: .
    image: hiilikartta-data-service
    command: /bin/bash -lc "cd /app && poetry run saq --workers 25 app.saq_worker.settings --web"
    env_file:
      - ./.env
    environment:
      REDIS_HOST: "redis-prod"
      REDIS_PORT: "6379"
    volumes:
      - ./project:/usr/src/app
      - .:/app:z
      - ./.cache:/root/.cache
    ports:
      - "127.0.0.1:${SAQ_WEB_PORT}:8080"
    networks:
      - proxy-net
    depends_on:
      app-prod:
        condition: service_started
      redis-prod:
        condition: service_started
    restart: unless-stopped

  redis-prod:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ${REDIS_DATA_PATH}:/data
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - proxy-net

  state-db-test:
    image: postgres:15-alpine
    profiles:
      - test
    environment:
      POSTGRES_DB: ${STATE_PG_TEST_DB}
      POSTGRES_USER: ${STATE_PG_TEST_USER}
      POSTGRES_PASSWORD: ${STATE_PG_TEST_PASSWORD}
    volumes:
      - state-db-test-data:/var/lib/postgresql/data
    networks:
      - proxy-net

  autoheal-prod:
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - DOCKER_SOCK=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
volumes:
  state-db-test-data:
