version: "3.8"

services:
  app:
    container_name: hiilikartta-data
    build: .
    env_file:
      - ./.env
    ports:
      - "${DEV_PORT}:80"
      - "${NOTEBOOK_PORT}:8888"
    volumes:
      - .:/app:z
      - ./.cache:/root/.cache
      # - ./.conda-pkgs:/root/conda/pkgs
      - ./.vscode-server:/root/.vscode-server
      # - ${REMOTE_DB_SSH_KEY}:/root/.ssh/remote_db_rsa:z
      - ${GIT_SSH_KEY}:/root/.ssh/id_rsa:z
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    networks:
      - climate-map-network

networks:
  climate-map-network:
    external: true
# volumes:
#   poetry-cache:
