version: "3.8"

services:
  app:
    container_name: hiilikartta-data
    build: .
    env_file:
      - ./.env
    ports:
      - "${DEV_PORT}:80"
    volumes:
      - .:/app:z
    entrypoint: "poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 80"
    # entrypoint: "/bin/bash /app/docker-entrypoint.sh"
