version: "3.8"

services:
  app:
    container_name: hiilikartta-data
    build: .
    env_file:
      - ./.env
    ports:
      - "${DEV_PORT}:80"
    volumes:
      - .:/app:z
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
