version: "3.8"

services:
  app:
    container_name: hiilikartta-data
    build: .
    env_file:
      - ./.env
    ports:
      - "${DEV_PORT}:80"
      - "${NOTEBOOK_PORT}:8888"
    volumes:
      - .:/app:z
      - ./.cache:/root/.cache
      # - ./.conda-pkgs:/root/conda/pkgs
      - ./.vscode-server:/root/.vscode-server
      - ${SSH_KEY_PATH}:/root/.ssh/id_rsa:z
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]

# volumes:
#   poetry-cache:
