"""Add last_accessed_ts

Revision ID: 218b9d22b748
Revises: 63fa38593e78
Create Date: 2024-03-15 16:17:22.359081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '218b9d22b748'
down_revision: Union[str, None] = '63fa38593e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('last_accessed_ts', postgresql.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'last_accessed_ts')
    # ### end Alembic commands ###
