"""initial squashed schema

Revision ID: 4445a2a04ed8
Revises: 
Create Date: 2025-12-05 14:35:58.550872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '643dcd0a493b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Required for gen_random_uuid() default values.
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    sa.Enum('PROCESSING', 'FINISHED', 'ERROR', 'NOT_STARTED', name='calculation_status_enum').create(op.get_bind())
    op.create_table('plan',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ui_id', sa.UUID(), nullable=False),
    sa.Column('visible_ui_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_ts', postgresql.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_ts', postgresql.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('saved_ts', postgresql.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('last_accessed_ts', postgresql.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('total_indices', sa.Integer(), nullable=True),
    sa.Column('last_index', sa.Integer(), nullable=True),
    sa.Column('last_area_calculation_status', postgresql.ENUM('PROCESSING', 'FINISHED', 'ERROR', 'NOT_STARTED', name='calculation_status_enum', create_type=False), nullable=True),
    sa.Column('last_area_calculation_retries', sa.Integer(), nullable=True),
    sa.Column('calculated_ts', sa.DateTime(), nullable=True),
    sa.Column('calculation_updated_ts', sa.DateTime(), nullable=True),
    sa.Column('calculation_status', postgresql.ENUM('PROCESSING', 'FINISHED', 'ERROR', 'NOT_STARTED', name='calculation_status_enum', create_type=False), nullable=True),
    sa.Column('report_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_totals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ui_id', name='ui_id_unique')
    )
    op.create_index(op.f('ix_plan_ui_id'), 'plan', ['ui_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_ui_id'), table_name='plan')
    op.drop_table('plan')
    sa.Enum('PROCESSING', 'FINISHED', 'ERROR', 'NOT_STARTED', name='calculation_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
